name: "Deploy-App-Services"

on:
  workflow_call:
    inputs:
      AZURE_WEBAPP_NAME:  # set this to your function app name on Azure
        required: true
        type: string
      AZURE_WEBAPP_PACKAGE_PATH: # set this to the path to your function app project, defaults to the repository root
        required: true
        type: string
      DOTNET_VERSION: # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')
        required: true
        type: string
      ENVIRONMENT: # set this to the environment
        required: true
        type: string
    secrets:
      AZUREAPPSERVICE_PUBLISHPROFILE:
        required: true
jobs:
  build:
    runs-on: windows-latest

    permissions:
      id-token: write
      contents: read
      issues: read
      checks: write
      pull-requests: write

    environment: ${{ inputs.ENVIRONMENT }}
    
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
      
      # Setup .NET Core SDK
      - name: Setup DotNet ${{ inputs.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='${{ inputs.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ inputs.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          slot-name: ${{ inputs.ENVIRONMENT }}
          package: '${{ inputs.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
