name: deploy app service

on:
  push:
    branches:
      - main

jobs:
  call:
    uses: ./.github/workflows/az-app-service.yaml
    with:
      AZURE_WEBAPP_NAME: 'TestMyFirstApp'
      AZURE_WEBAPP_PACKAGE_PATH: '.'
      DOTNET_VERSION: '8.x'
      ENVIRONMENT: 'DEV'
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E6E8788BF7FE4BF6BB5E22D32680F314 }}